#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KK5D")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 확장성 메서드 정의
    partial void OnCreated();
    partial void Insertmilstk(milstk instance);
    partial void Updatemilstk(milstk instance);
    partial void Deletemilstk(milstk instance);
    partial void Insertmiplti(miplti instance);
    partial void Updatemiplti(miplti instance);
    partial void Deletemiplti(miplti instance);
    partial void Inserttbindx(tbindx instance);
    partial void Updatetbindx(tbindx instance);
    partial void Deletetbindx(tbindx instance);
    partial void Inserttbscer(tbscer instance);
    partial void Updatetbscer(tbscer instance);
    partial void Deletetbscer(tbscer instance);
    partial void Inserttibarc(tibarc instance);
    partial void Updatetibarc(tibarc instance);
    partial void Deletetibarc(tibarc instance);
    partial void Inserttbstat(tbstat instance);
    partial void Updatetbstat(tbstat instance);
    partial void Deletetbstat(tbstat instance);
    partial void Inserttbcnvc(tbcnvc instance);
    partial void Updatetbcnvc(tbcnvc instance);
    partial void Deletetbcnvc(tbcnvc instance);
    partial void Inserttbscrc(tbscrc instance);
    partial void Updatetbscrc(tbscrc instance);
    partial void Deletetbscrc(tbscrc instance);
    #endregion
		
		public DBDataContext() : 
				base("Data Source=CSON01;Initial Catalog=IPK_RCP;Persist Security Info=True;User ID=aw_" +
						"sa;Password=\"moNey=918+\";Encrypt=False;TrustServerCertificate=True", mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<milstk> milstks
		{
			get
			{
				return this.GetTable<milstk>();
			}
		}
		
		public System.Data.Linq.Table<miplti> mipltis
		{
			get
			{
				return this.GetTable<miplti>();
			}
		}
		
		public System.Data.Linq.Table<tbindx> tbindxes
		{
			get
			{
				return this.GetTable<tbindx>();
			}
		}
		
		public System.Data.Linq.Table<tbscer> tbscers
		{
			get
			{
				return this.GetTable<tbscer>();
			}
		}
		
		public System.Data.Linq.Table<tibarc> tibarcs
		{
			get
			{
				return this.GetTable<tibarc>();
			}
		}
		
		public System.Data.Linq.Table<tbstat> tbstats
		{
			get
			{
				return this.GetTable<tbstat>();
			}
		}
		
		public System.Data.Linq.Table<tbcnvc> tbcnvcs
		{
			get
			{
				return this.GetTable<tbcnvc>();
			}
		}
		
		public System.Data.Linq.Table<tbscrc> tbscrcs
		{
			get
			{
				return this.GetTable<tbscrc>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime10")]
		public int p_curgetdatetime10([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime19")]
		public int p_curgetdatetime19([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(19)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime14")]
		public int p_curgetdatetime14([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(14)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_get_indx_jno")]
		public int p_get_indx_jno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string ac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(18)")] ref string rstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ac, rstr);
			rstr = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_get_hogi")]
		public int p_get_hogi([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string lstk, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] ref string hogi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lstk, hogi);
			hogi = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_tilock")]
		public int p_tilock()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_inpt_cancel")]
		public int u_inpt_cancel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gb, apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_ymove_finish")]
		public int u_ymove_finish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_inpt_double")]
		public int u_inpt_double([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_inpt_finish")]
		public int u_inpt_finish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gb, apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_move_cancel")]
		public int u_move_cancel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_move_finish")]
		public int u_move_finish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_oupt_cancel")]
		public int u_oupt_cancel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_oupt_empt")]
		public int u_oupt_empt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string aotype, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aotype, apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_oupt_finish")]
		public int u_oupt_finish([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.u_ymove_cancel")]
		public int u_ymove_cancel([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8)")] string apltn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(7)")] string alstk)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), apltn, alstk);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.milstk")]
	public partial class milstk : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _lstk_no;
		
		private string _lstk_bk;
		
		private string _lstk_by;
		
		private string _lstk_lv;
		
		private string _lstk_hogi;
		
		private string _lstk_use;
		
		private string _lstk_srch;
		
		private string _lstk_flag;
		
		private string _lstk_io;
		
		private string _lstk_stat;
		
		private string _lstk_type;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlstk_noChanging(string value);
    partial void Onlstk_noChanged();
    partial void Onlstk_bkChanging(string value);
    partial void Onlstk_bkChanged();
    partial void Onlstk_byChanging(string value);
    partial void Onlstk_byChanged();
    partial void Onlstk_lvChanging(string value);
    partial void Onlstk_lvChanged();
    partial void Onlstk_hogiChanging(string value);
    partial void Onlstk_hogiChanged();
    partial void Onlstk_useChanging(string value);
    partial void Onlstk_useChanged();
    partial void Onlstk_srchChanging(string value);
    partial void Onlstk_srchChanged();
    partial void Onlstk_flagChanging(string value);
    partial void Onlstk_flagChanged();
    partial void Onlstk_ioChanging(string value);
    partial void Onlstk_ioChanged();
    partial void Onlstk_statChanging(string value);
    partial void Onlstk_statChanged();
    partial void Onlstk_typeChanging(string value);
    partial void Onlstk_typeChanged();
    #endregion
		
		public milstk()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_no", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string lstk_no
		{
			get
			{
				return this._lstk_no;
			}
			set
			{
				if ((this._lstk_no != value))
				{
					this.Onlstk_noChanging(value);
					this.SendPropertyChanging();
					this._lstk_no = value;
					this.SendPropertyChanged("lstk_no");
					this.Onlstk_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_bk", DbType="VarChar(2)")]
		public string lstk_bk
		{
			get
			{
				return this._lstk_bk;
			}
			set
			{
				if ((this._lstk_bk != value))
				{
					this.Onlstk_bkChanging(value);
					this.SendPropertyChanging();
					this._lstk_bk = value;
					this.SendPropertyChanged("lstk_bk");
					this.Onlstk_bkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_by", DbType="VarChar(2)")]
		public string lstk_by
		{
			get
			{
				return this._lstk_by;
			}
			set
			{
				if ((this._lstk_by != value))
				{
					this.Onlstk_byChanging(value);
					this.SendPropertyChanging();
					this._lstk_by = value;
					this.SendPropertyChanged("lstk_by");
					this.Onlstk_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_lv", DbType="VarChar(2)")]
		public string lstk_lv
		{
			get
			{
				return this._lstk_lv;
			}
			set
			{
				if ((this._lstk_lv != value))
				{
					this.Onlstk_lvChanging(value);
					this.SendPropertyChanging();
					this._lstk_lv = value;
					this.SendPropertyChanged("lstk_lv");
					this.Onlstk_lvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_hogi", DbType="VarChar(2)")]
		public string lstk_hogi
		{
			get
			{
				return this._lstk_hogi;
			}
			set
			{
				if ((this._lstk_hogi != value))
				{
					this.Onlstk_hogiChanging(value);
					this.SendPropertyChanging();
					this._lstk_hogi = value;
					this.SendPropertyChanged("lstk_hogi");
					this.Onlstk_hogiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_use", DbType="VarChar(1)")]
		public string lstk_use
		{
			get
			{
				return this._lstk_use;
			}
			set
			{
				if ((this._lstk_use != value))
				{
					this.Onlstk_useChanging(value);
					this.SendPropertyChanging();
					this._lstk_use = value;
					this.SendPropertyChanged("lstk_use");
					this.Onlstk_useChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_srch", DbType="VarChar(6)")]
		public string lstk_srch
		{
			get
			{
				return this._lstk_srch;
			}
			set
			{
				if ((this._lstk_srch != value))
				{
					this.Onlstk_srchChanging(value);
					this.SendPropertyChanging();
					this._lstk_srch = value;
					this.SendPropertyChanged("lstk_srch");
					this.Onlstk_srchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_flag", DbType="VarChar(1)")]
		public string lstk_flag
		{
			get
			{
				return this._lstk_flag;
			}
			set
			{
				if ((this._lstk_flag != value))
				{
					this.Onlstk_flagChanging(value);
					this.SendPropertyChanging();
					this._lstk_flag = value;
					this.SendPropertyChanged("lstk_flag");
					this.Onlstk_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_io", DbType="VarChar(1)")]
		public string lstk_io
		{
			get
			{
				return this._lstk_io;
			}
			set
			{
				if ((this._lstk_io != value))
				{
					this.Onlstk_ioChanging(value);
					this.SendPropertyChanging();
					this._lstk_io = value;
					this.SendPropertyChanged("lstk_io");
					this.Onlstk_ioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_stat", DbType="VarChar(2)")]
		public string lstk_stat
		{
			get
			{
				return this._lstk_stat;
			}
			set
			{
				if ((this._lstk_stat != value))
				{
					this.Onlstk_statChanging(value);
					this.SendPropertyChanging();
					this._lstk_stat = value;
					this.SendPropertyChanged("lstk_stat");
					this.Onlstk_statChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lstk_type", DbType="VarChar(1)")]
		public string lstk_type
		{
			get
			{
				return this._lstk_type;
			}
			set
			{
				if ((this._lstk_type != value))
				{
					this.Onlstk_typeChanging(value);
					this.SendPropertyChanging();
					this._lstk_type = value;
					this.SendPropertyChanged("lstk_type");
					this.Onlstk_typeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.miplti")]
	public partial class miplti : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _plti_pltno;
		
		private string _plti_lstk;
		
		private string _plti_prod;
		
		private string _plti_pdesc;
		
		private string _plti_oprod;
		
		private string _plti_loc;
		
		private string _plti_lot;
		
		private string _plti_bestq;
		
		private System.Nullable<decimal> _plti_pksz;
		
		private string _plti_remark;
		
		private string _plti_icust;
		
		private System.Nullable<decimal> _plti_stok;
		
		private System.Nullable<decimal> _plti_rqty;
		
		private string _plti_cycl_date;
		
		private string _plti_idate;
		
		private string _plti_itime;
		
		private string _plti_flag;
		
		private string _plti_label;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplti_pltnoChanging(string value);
    partial void Onplti_pltnoChanged();
    partial void Onplti_lstkChanging(string value);
    partial void Onplti_lstkChanged();
    partial void Onplti_prodChanging(string value);
    partial void Onplti_prodChanged();
    partial void Onplti_pdescChanging(string value);
    partial void Onplti_pdescChanged();
    partial void Onplti_oprodChanging(string value);
    partial void Onplti_oprodChanged();
    partial void Onplti_locChanging(string value);
    partial void Onplti_locChanged();
    partial void Onplti_lotChanging(string value);
    partial void Onplti_lotChanged();
    partial void Onplti_bestqChanging(string value);
    partial void Onplti_bestqChanged();
    partial void Onplti_pkszChanging(System.Nullable<decimal> value);
    partial void Onplti_pkszChanged();
    partial void Onplti_remarkChanging(string value);
    partial void Onplti_remarkChanged();
    partial void Onplti_icustChanging(string value);
    partial void Onplti_icustChanged();
    partial void Onplti_stokChanging(System.Nullable<decimal> value);
    partial void Onplti_stokChanged();
    partial void Onplti_rqtyChanging(System.Nullable<decimal> value);
    partial void Onplti_rqtyChanged();
    partial void Onplti_cycl_dateChanging(string value);
    partial void Onplti_cycl_dateChanged();
    partial void Onplti_idateChanging(string value);
    partial void Onplti_idateChanged();
    partial void Onplti_itimeChanging(string value);
    partial void Onplti_itimeChanged();
    partial void Onplti_flagChanging(string value);
    partial void Onplti_flagChanged();
    partial void Onplti_labelChanging(string value);
    partial void Onplti_labelChanged();
    #endregion
		
		public miplti()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_pltno", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_pltno
		{
			get
			{
				return this._plti_pltno;
			}
			set
			{
				if ((this._plti_pltno != value))
				{
					this.Onplti_pltnoChanging(value);
					this.SendPropertyChanging();
					this._plti_pltno = value;
					this.SendPropertyChanged("plti_pltno");
					this.Onplti_pltnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_lstk", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_lstk
		{
			get
			{
				return this._plti_lstk;
			}
			set
			{
				if ((this._plti_lstk != value))
				{
					this.Onplti_lstkChanging(value);
					this.SendPropertyChanging();
					this._plti_lstk = value;
					this.SendPropertyChanged("plti_lstk");
					this.Onplti_lstkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_prod", DbType="VarChar(18) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_prod
		{
			get
			{
				return this._plti_prod;
			}
			set
			{
				if ((this._plti_prod != value))
				{
					this.Onplti_prodChanging(value);
					this.SendPropertyChanging();
					this._plti_prod = value;
					this.SendPropertyChanged("plti_prod");
					this.Onplti_prodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_pdesc", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string plti_pdesc
		{
			get
			{
				return this._plti_pdesc;
			}
			set
			{
				if ((this._plti_pdesc != value))
				{
					this.Onplti_pdescChanging(value);
					this.SendPropertyChanging();
					this._plti_pdesc = value;
					this.SendPropertyChanged("plti_pdesc");
					this.Onplti_pdescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_oprod", DbType="VarChar(18)")]
		public string plti_oprod
		{
			get
			{
				return this._plti_oprod;
			}
			set
			{
				if ((this._plti_oprod != value))
				{
					this.Onplti_oprodChanging(value);
					this.SendPropertyChanging();
					this._plti_oprod = value;
					this.SendPropertyChanged("plti_oprod");
					this.Onplti_oprodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_loc", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_loc
		{
			get
			{
				return this._plti_loc;
			}
			set
			{
				if ((this._plti_loc != value))
				{
					this.Onplti_locChanging(value);
					this.SendPropertyChanging();
					this._plti_loc = value;
					this.SendPropertyChanged("plti_loc");
					this.Onplti_locChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_lot", DbType="VarChar(18) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_lot
		{
			get
			{
				return this._plti_lot;
			}
			set
			{
				if ((this._plti_lot != value))
				{
					this.Onplti_lotChanging(value);
					this.SendPropertyChanging();
					this._plti_lot = value;
					this.SendPropertyChanged("plti_lot");
					this.Onplti_lotChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_bestq", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string plti_bestq
		{
			get
			{
				return this._plti_bestq;
			}
			set
			{
				if ((this._plti_bestq != value))
				{
					this.Onplti_bestqChanging(value);
					this.SendPropertyChanging();
					this._plti_bestq = value;
					this.SendPropertyChanged("plti_bestq");
					this.Onplti_bestqChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_pksz", DbType="Decimal(7,2)")]
		public System.Nullable<decimal> plti_pksz
		{
			get
			{
				return this._plti_pksz;
			}
			set
			{
				if ((this._plti_pksz != value))
				{
					this.Onplti_pkszChanging(value);
					this.SendPropertyChanging();
					this._plti_pksz = value;
					this.SendPropertyChanged("plti_pksz");
					this.Onplti_pkszChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_remark", DbType="VarChar(40)")]
		public string plti_remark
		{
			get
			{
				return this._plti_remark;
			}
			set
			{
				if ((this._plti_remark != value))
				{
					this.Onplti_remarkChanging(value);
					this.SendPropertyChanging();
					this._plti_remark = value;
					this.SendPropertyChanged("plti_remark");
					this.Onplti_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_icust", DbType="VarChar(40)")]
		public string plti_icust
		{
			get
			{
				return this._plti_icust;
			}
			set
			{
				if ((this._plti_icust != value))
				{
					this.Onplti_icustChanging(value);
					this.SendPropertyChanging();
					this._plti_icust = value;
					this.SendPropertyChanged("plti_icust");
					this.Onplti_icustChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_stok", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> plti_stok
		{
			get
			{
				return this._plti_stok;
			}
			set
			{
				if ((this._plti_stok != value))
				{
					this.Onplti_stokChanging(value);
					this.SendPropertyChanging();
					this._plti_stok = value;
					this.SendPropertyChanged("plti_stok");
					this.Onplti_stokChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_rqty", DbType="Decimal(8,0)")]
		public System.Nullable<decimal> plti_rqty
		{
			get
			{
				return this._plti_rqty;
			}
			set
			{
				if ((this._plti_rqty != value))
				{
					this.Onplti_rqtyChanging(value);
					this.SendPropertyChanging();
					this._plti_rqty = value;
					this.SendPropertyChanged("plti_rqty");
					this.Onplti_rqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_cycl_date", DbType="VarChar(10)")]
		public string plti_cycl_date
		{
			get
			{
				return this._plti_cycl_date;
			}
			set
			{
				if ((this._plti_cycl_date != value))
				{
					this.Onplti_cycl_dateChanging(value);
					this.SendPropertyChanging();
					this._plti_cycl_date = value;
					this.SendPropertyChanged("plti_cycl_date");
					this.Onplti_cycl_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_idate", DbType="VarChar(10)")]
		public string plti_idate
		{
			get
			{
				return this._plti_idate;
			}
			set
			{
				if ((this._plti_idate != value))
				{
					this.Onplti_idateChanging(value);
					this.SendPropertyChanging();
					this._plti_idate = value;
					this.SendPropertyChanged("plti_idate");
					this.Onplti_idateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_itime", DbType="VarChar(8)")]
		public string plti_itime
		{
			get
			{
				return this._plti_itime;
			}
			set
			{
				if ((this._plti_itime != value))
				{
					this.Onplti_itimeChanging(value);
					this.SendPropertyChanging();
					this._plti_itime = value;
					this.SendPropertyChanged("plti_itime");
					this.Onplti_itimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_flag", DbType="VarChar(1)")]
		public string plti_flag
		{
			get
			{
				return this._plti_flag;
			}
			set
			{
				if ((this._plti_flag != value))
				{
					this.Onplti_flagChanging(value);
					this.SendPropertyChanging();
					this._plti_flag = value;
					this.SendPropertyChanged("plti_flag");
					this.Onplti_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plti_label", DbType="VarChar(1)")]
		public string plti_label
		{
			get
			{
				return this._plti_label;
			}
			set
			{
				if ((this._plti_label != value))
				{
					this.Onplti_labelChanging(value);
					this.SendPropertyChanging();
					this._plti_label = value;
					this.SendPropertyChanged("plti_label");
					this.Onplti_labelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbindx")]
	public partial class tbindx : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _indx_jno;
		
		private string _indx_indx;
		
		private string _indx_gubn;
		
		private string _indx_jio;
		
		private string _indx_hogi;
		
		private string _indx_fstn;
		
		private string _indx_tstn;
		
		private string _indx_pltn;
		
		private string _indx_lstk;
		
		private string _indx_xmov;
		
		private string _indx_edat;
		
		private string _indx_sflg;
		
		private string _indx_uflg;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onindx_jnoChanging(string value);
    partial void Onindx_jnoChanged();
    partial void Onindx_indxChanging(string value);
    partial void Onindx_indxChanged();
    partial void Onindx_gubnChanging(string value);
    partial void Onindx_gubnChanged();
    partial void Onindx_jioChanging(string value);
    partial void Onindx_jioChanged();
    partial void Onindx_hogiChanging(string value);
    partial void Onindx_hogiChanged();
    partial void Onindx_fstnChanging(string value);
    partial void Onindx_fstnChanged();
    partial void Onindx_tstnChanging(string value);
    partial void Onindx_tstnChanged();
    partial void Onindx_pltnChanging(string value);
    partial void Onindx_pltnChanged();
    partial void Onindx_lstkChanging(string value);
    partial void Onindx_lstkChanged();
    partial void Onindx_xmovChanging(string value);
    partial void Onindx_xmovChanged();
    partial void Onindx_edatChanging(string value);
    partial void Onindx_edatChanged();
    partial void Onindx_sflgChanging(string value);
    partial void Onindx_sflgChanged();
    partial void Onindx_uflgChanging(string value);
    partial void Onindx_uflgChanged();
    #endregion
		
		public tbindx()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_jno", DbType="VarChar(18) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string indx_jno
		{
			get
			{
				return this._indx_jno;
			}
			set
			{
				if ((this._indx_jno != value))
				{
					this.Onindx_jnoChanging(value);
					this.SendPropertyChanging();
					this._indx_jno = value;
					this.SendPropertyChanged("indx_jno");
					this.Onindx_jnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_indx", DbType="VarChar(4)")]
		public string indx_indx
		{
			get
			{
				return this._indx_indx;
			}
			set
			{
				if ((this._indx_indx != value))
				{
					this.Onindx_indxChanging(value);
					this.SendPropertyChanging();
					this._indx_indx = value;
					this.SendPropertyChanged("indx_indx");
					this.Onindx_indxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_gubn", DbType="VarChar(1)")]
		public string indx_gubn
		{
			get
			{
				return this._indx_gubn;
			}
			set
			{
				if ((this._indx_gubn != value))
				{
					this.Onindx_gubnChanging(value);
					this.SendPropertyChanging();
					this._indx_gubn = value;
					this.SendPropertyChanged("indx_gubn");
					this.Onindx_gubnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_jio", DbType="VarChar(1)")]
		public string indx_jio
		{
			get
			{
				return this._indx_jio;
			}
			set
			{
				if ((this._indx_jio != value))
				{
					this.Onindx_jioChanging(value);
					this.SendPropertyChanging();
					this._indx_jio = value;
					this.SendPropertyChanged("indx_jio");
					this.Onindx_jioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_hogi", DbType="VarChar(1)")]
		public string indx_hogi
		{
			get
			{
				return this._indx_hogi;
			}
			set
			{
				if ((this._indx_hogi != value))
				{
					this.Onindx_hogiChanging(value);
					this.SendPropertyChanging();
					this._indx_hogi = value;
					this.SendPropertyChanged("indx_hogi");
					this.Onindx_hogiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_fstn", DbType="VarChar(2)")]
		public string indx_fstn
		{
			get
			{
				return this._indx_fstn;
			}
			set
			{
				if ((this._indx_fstn != value))
				{
					this.Onindx_fstnChanging(value);
					this.SendPropertyChanging();
					this._indx_fstn = value;
					this.SendPropertyChanged("indx_fstn");
					this.Onindx_fstnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_tstn", DbType="VarChar(2)")]
		public string indx_tstn
		{
			get
			{
				return this._indx_tstn;
			}
			set
			{
				if ((this._indx_tstn != value))
				{
					this.Onindx_tstnChanging(value);
					this.SendPropertyChanging();
					this._indx_tstn = value;
					this.SendPropertyChanged("indx_tstn");
					this.Onindx_tstnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_pltn", DbType="VarChar(8)")]
		public string indx_pltn
		{
			get
			{
				return this._indx_pltn;
			}
			set
			{
				if ((this._indx_pltn != value))
				{
					this.Onindx_pltnChanging(value);
					this.SendPropertyChanging();
					this._indx_pltn = value;
					this.SendPropertyChanged("indx_pltn");
					this.Onindx_pltnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_lstk", DbType="VarChar(7)")]
		public string indx_lstk
		{
			get
			{
				return this._indx_lstk;
			}
			set
			{
				if ((this._indx_lstk != value))
				{
					this.Onindx_lstkChanging(value);
					this.SendPropertyChanging();
					this._indx_lstk = value;
					this.SendPropertyChanged("indx_lstk");
					this.Onindx_lstkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_xmov", DbType="VarChar(1)")]
		public string indx_xmov
		{
			get
			{
				return this._indx_xmov;
			}
			set
			{
				if ((this._indx_xmov != value))
				{
					this.Onindx_xmovChanging(value);
					this.SendPropertyChanging();
					this._indx_xmov = value;
					this.SendPropertyChanged("indx_xmov");
					this.Onindx_xmovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_edat", DbType="VarChar(14)")]
		public string indx_edat
		{
			get
			{
				return this._indx_edat;
			}
			set
			{
				if ((this._indx_edat != value))
				{
					this.Onindx_edatChanging(value);
					this.SendPropertyChanging();
					this._indx_edat = value;
					this.SendPropertyChanged("indx_edat");
					this.Onindx_edatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_sflg", DbType="VarChar(1)")]
		public string indx_sflg
		{
			get
			{
				return this._indx_sflg;
			}
			set
			{
				if ((this._indx_sflg != value))
				{
					this.Onindx_sflgChanging(value);
					this.SendPropertyChanging();
					this._indx_sflg = value;
					this.SendPropertyChanged("indx_sflg");
					this.Onindx_sflgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_indx_uflg", DbType="VarChar(1)")]
		public string indx_uflg
		{
			get
			{
				return this._indx_uflg;
			}
			set
			{
				if ((this._indx_uflg != value))
				{
					this.Onindx_uflgChanging(value);
					this.SendPropertyChanging();
					this._indx_uflg = value;
					this.SendPropertyChanged("indx_uflg");
					this.Onindx_uflgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbscer")]
	public partial class tbscer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _scer_ercd;
		
		private string _scer_mesg;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onscer_ercdChanging(string value);
    partial void Onscer_ercdChanged();
    partial void Onscer_mesgChanging(string value);
    partial void Onscer_mesgChanged();
    #endregion
		
		public tbscer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scer_ercd", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string scer_ercd
		{
			get
			{
				return this._scer_ercd;
			}
			set
			{
				if ((this._scer_ercd != value))
				{
					this.Onscer_ercdChanging(value);
					this.SendPropertyChanging();
					this._scer_ercd = value;
					this.SendPropertyChanged("scer_ercd");
					this.Onscer_ercdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scer_mesg", DbType="VarChar(60)")]
		public string scer_mesg
		{
			get
			{
				return this._scer_mesg;
			}
			set
			{
				if ((this._scer_mesg != value))
				{
					this.Onscer_mesgChanging(value);
					this.SendPropertyChanging();
					this._scer_mesg = value;
					this.SendPropertyChanged("scer_mesg");
					this.Onscer_mesgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tibarc")]
	public partial class tibarc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _barc_key;
		
		private string _barc_pltno;
		
		private System.Nullable<System.DateTime> _barc_date;
		
		private string _barc_msg;
		
		private string _barc_flag;
		
		private string _cvc_msg;
		
		private string _cvc_flag;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbarc_keyChanging(string value);
    partial void Onbarc_keyChanged();
    partial void Onbarc_pltnoChanging(string value);
    partial void Onbarc_pltnoChanged();
    partial void Onbarc_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbarc_dateChanged();
    partial void Onbarc_msgChanging(string value);
    partial void Onbarc_msgChanged();
    partial void Onbarc_flagChanging(string value);
    partial void Onbarc_flagChanged();
    partial void Oncvc_msgChanging(string value);
    partial void Oncvc_msgChanged();
    partial void Oncvc_flagChanging(string value);
    partial void Oncvc_flagChanged();
    #endregion
		
		public tibarc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barc_key", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string barc_key
		{
			get
			{
				return this._barc_key;
			}
			set
			{
				if ((this._barc_key != value))
				{
					this.Onbarc_keyChanging(value);
					this.SendPropertyChanging();
					this._barc_key = value;
					this.SendPropertyChanged("barc_key");
					this.Onbarc_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barc_pltno", DbType="VarChar(8)")]
		public string barc_pltno
		{
			get
			{
				return this._barc_pltno;
			}
			set
			{
				if ((this._barc_pltno != value))
				{
					this.Onbarc_pltnoChanging(value);
					this.SendPropertyChanging();
					this._barc_pltno = value;
					this.SendPropertyChanged("barc_pltno");
					this.Onbarc_pltnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barc_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> barc_date
		{
			get
			{
				return this._barc_date;
			}
			set
			{
				if ((this._barc_date != value))
				{
					this.Onbarc_dateChanging(value);
					this.SendPropertyChanging();
					this._barc_date = value;
					this.SendPropertyChanged("barc_date");
					this.Onbarc_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barc_msg", DbType="VarChar(50)")]
		public string barc_msg
		{
			get
			{
				return this._barc_msg;
			}
			set
			{
				if ((this._barc_msg != value))
				{
					this.Onbarc_msgChanging(value);
					this.SendPropertyChanging();
					this._barc_msg = value;
					this.SendPropertyChanged("barc_msg");
					this.Onbarc_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barc_flag", DbType="VarChar(1)")]
		public string barc_flag
		{
			get
			{
				return this._barc_flag;
			}
			set
			{
				if ((this._barc_flag != value))
				{
					this.Onbarc_flagChanging(value);
					this.SendPropertyChanging();
					this._barc_flag = value;
					this.SendPropertyChanged("barc_flag");
					this.Onbarc_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvc_msg", DbType="VarChar(50)")]
		public string cvc_msg
		{
			get
			{
				return this._cvc_msg;
			}
			set
			{
				if ((this._cvc_msg != value))
				{
					this.Oncvc_msgChanging(value);
					this.SendPropertyChanging();
					this._cvc_msg = value;
					this.SendPropertyChanged("cvc_msg");
					this.Oncvc_msgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cvc_flag", DbType="VarChar(1)")]
		public string cvc_flag
		{
			get
			{
				return this._cvc_flag;
			}
			set
			{
				if ((this._cvc_flag != value))
				{
					this.Oncvc_flagChanging(value);
					this.SendPropertyChanging();
					this._cvc_flag = value;
					this.SendPropertyChanged("cvc_flag");
					this.Oncvc_flagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbstat")]
	public partial class tbstat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _stat_key;
		
		private string _stat_imode;
		
		private string _stat_ipath;
		
		private string _stat_barm;
		
		private string _stat_dplt;
		
		private string _stat_lr;
		
		private string _stat_out;
		
		private string _stat_auto_load;
		
		private string _stat_resp_load;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstat_keyChanging(string value);
    partial void Onstat_keyChanged();
    partial void Onstat_imodeChanging(string value);
    partial void Onstat_imodeChanged();
    partial void Onstat_ipathChanging(string value);
    partial void Onstat_ipathChanged();
    partial void Onstat_barmChanging(string value);
    partial void Onstat_barmChanged();
    partial void Onstat_dpltChanging(string value);
    partial void Onstat_dpltChanged();
    partial void Onstat_lrChanging(string value);
    partial void Onstat_lrChanged();
    partial void Onstat_outChanging(string value);
    partial void Onstat_outChanged();
    partial void Onstat_auto_loadChanging(string value);
    partial void Onstat_auto_loadChanged();
    partial void Onstat_resp_loadChanging(string value);
    partial void Onstat_resp_loadChanged();
    #endregion
		
		public tbstat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_key", DbType="VarChar(1) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string stat_key
		{
			get
			{
				return this._stat_key;
			}
			set
			{
				if ((this._stat_key != value))
				{
					this.Onstat_keyChanging(value);
					this.SendPropertyChanging();
					this._stat_key = value;
					this.SendPropertyChanged("stat_key");
					this.Onstat_keyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_imode", DbType="VarChar(1)")]
		public string stat_imode
		{
			get
			{
				return this._stat_imode;
			}
			set
			{
				if ((this._stat_imode != value))
				{
					this.Onstat_imodeChanging(value);
					this.SendPropertyChanging();
					this._stat_imode = value;
					this.SendPropertyChanged("stat_imode");
					this.Onstat_imodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_ipath", DbType="VarChar(1)")]
		public string stat_ipath
		{
			get
			{
				return this._stat_ipath;
			}
			set
			{
				if ((this._stat_ipath != value))
				{
					this.Onstat_ipathChanging(value);
					this.SendPropertyChanging();
					this._stat_ipath = value;
					this.SendPropertyChanged("stat_ipath");
					this.Onstat_ipathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_barm", DbType="VarChar(1)")]
		public string stat_barm
		{
			get
			{
				return this._stat_barm;
			}
			set
			{
				if ((this._stat_barm != value))
				{
					this.Onstat_barmChanging(value);
					this.SendPropertyChanging();
					this._stat_barm = value;
					this.SendPropertyChanged("stat_barm");
					this.Onstat_barmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_dplt", DbType="VarChar(1)")]
		public string stat_dplt
		{
			get
			{
				return this._stat_dplt;
			}
			set
			{
				if ((this._stat_dplt != value))
				{
					this.Onstat_dpltChanging(value);
					this.SendPropertyChanging();
					this._stat_dplt = value;
					this.SendPropertyChanged("stat_dplt");
					this.Onstat_dpltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_lr", DbType="VarChar(1)")]
		public string stat_lr
		{
			get
			{
				return this._stat_lr;
			}
			set
			{
				if ((this._stat_lr != value))
				{
					this.Onstat_lrChanging(value);
					this.SendPropertyChanging();
					this._stat_lr = value;
					this.SendPropertyChanged("stat_lr");
					this.Onstat_lrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_out", DbType="VarChar(1)")]
		public string stat_out
		{
			get
			{
				return this._stat_out;
			}
			set
			{
				if ((this._stat_out != value))
				{
					this.Onstat_outChanging(value);
					this.SendPropertyChanging();
					this._stat_out = value;
					this.SendPropertyChanged("stat_out");
					this.Onstat_outChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_auto_load", DbType="VarChar(1)")]
		public string stat_auto_load
		{
			get
			{
				return this._stat_auto_load;
			}
			set
			{
				if ((this._stat_auto_load != value))
				{
					this.Onstat_auto_loadChanging(value);
					this.SendPropertyChanging();
					this._stat_auto_load = value;
					this.SendPropertyChanged("stat_auto_load");
					this.Onstat_auto_loadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stat_resp_load", DbType="VarChar(1)")]
		public string stat_resp_load
		{
			get
			{
				return this._stat_resp_load;
			}
			set
			{
				if ((this._stat_resp_load != value))
				{
					this.Onstat_resp_loadChanging(value);
					this.SendPropertyChanging();
					this._stat_resp_load = value;
					this.SendPropertyChanged("stat_resp_load");
					this.Onstat_resp_loadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbcnvc")]
	public partial class tbcnvc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cnvc_mode;
		
		private string _cnvc_ch01;
		
		private string _cnvc_ch02;
		
		private string _cnvc_ch03;
		
		private string _cnvc_ch04;
		
		private string _cnvc_ch05;
		
		private string _cnvc_ch06;
		
		private string _cnvc_op_onof;
		
		private string _cnvc_op_eror;
		
		private string _cnvc_job_no;
		
		private string _cnvc_jobno;
		
		private string _cnvc_buf_palt;
		
		private string _cnvc_ist_redy;
		
		private string _cnvc_ist_palt;
		
		private string _cnvc_ost_redy;
		
		private string _cnvc_ost_palt;
		
		private string _cnvc_21_rqst;
		
		private string _cnvc_22_rqst;
		
		private string _cnvc_remote;
		
		private string _cnvc_stop;
		
		private string _cnvc_comm;
		
		private string _cnvc_24_rqst;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncnvc_modeChanging(string value);
    partial void Oncnvc_modeChanged();
    partial void Oncnvc_ch01Changing(string value);
    partial void Oncnvc_ch01Changed();
    partial void Oncnvc_ch02Changing(string value);
    partial void Oncnvc_ch02Changed();
    partial void Oncnvc_ch03Changing(string value);
    partial void Oncnvc_ch03Changed();
    partial void Oncnvc_ch04Changing(string value);
    partial void Oncnvc_ch04Changed();
    partial void Oncnvc_ch05Changing(string value);
    partial void Oncnvc_ch05Changed();
    partial void Oncnvc_ch06Changing(string value);
    partial void Oncnvc_ch06Changed();
    partial void Oncnvc_op_onofChanging(string value);
    partial void Oncnvc_op_onofChanged();
    partial void Oncnvc_op_erorChanging(string value);
    partial void Oncnvc_op_erorChanged();
    partial void Oncnvc_job_noChanging(string value);
    partial void Oncnvc_job_noChanged();
    partial void Oncnvc_jobnoChanging(string value);
    partial void Oncnvc_jobnoChanged();
    partial void Oncnvc_buf_paltChanging(string value);
    partial void Oncnvc_buf_paltChanged();
    partial void Oncnvc_ist_redyChanging(string value);
    partial void Oncnvc_ist_redyChanged();
    partial void Oncnvc_ist_paltChanging(string value);
    partial void Oncnvc_ist_paltChanged();
    partial void Oncnvc_ost_redyChanging(string value);
    partial void Oncnvc_ost_redyChanged();
    partial void Oncnvc_ost_paltChanging(string value);
    partial void Oncnvc_ost_paltChanged();
    partial void Oncnvc_21_rqstChanging(string value);
    partial void Oncnvc_21_rqstChanged();
    partial void Oncnvc_22_rqstChanging(string value);
    partial void Oncnvc_22_rqstChanged();
    partial void Oncnvc_remoteChanging(string value);
    partial void Oncnvc_remoteChanged();
    partial void Oncnvc_stopChanging(string value);
    partial void Oncnvc_stopChanged();
    partial void Oncnvc_commChanging(string value);
    partial void Oncnvc_commChanged();
    partial void Oncnvc_24_rqstChanging(string value);
    partial void Oncnvc_24_rqstChanged();
    #endregion
		
		public tbcnvc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_mode", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cnvc_mode
		{
			get
			{
				return this._cnvc_mode;
			}
			set
			{
				if ((this._cnvc_mode != value))
				{
					this.Oncnvc_modeChanging(value);
					this.SendPropertyChanging();
					this._cnvc_mode = value;
					this.SendPropertyChanged("cnvc_mode");
					this.Oncnvc_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch01", DbType="VarChar(16)")]
		public string cnvc_ch01
		{
			get
			{
				return this._cnvc_ch01;
			}
			set
			{
				if ((this._cnvc_ch01 != value))
				{
					this.Oncnvc_ch01Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch01 = value;
					this.SendPropertyChanged("cnvc_ch01");
					this.Oncnvc_ch01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch02", DbType="VarChar(16)")]
		public string cnvc_ch02
		{
			get
			{
				return this._cnvc_ch02;
			}
			set
			{
				if ((this._cnvc_ch02 != value))
				{
					this.Oncnvc_ch02Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch02 = value;
					this.SendPropertyChanged("cnvc_ch02");
					this.Oncnvc_ch02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch03", DbType="VarChar(16)")]
		public string cnvc_ch03
		{
			get
			{
				return this._cnvc_ch03;
			}
			set
			{
				if ((this._cnvc_ch03 != value))
				{
					this.Oncnvc_ch03Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch03 = value;
					this.SendPropertyChanged("cnvc_ch03");
					this.Oncnvc_ch03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch04", DbType="VarChar(16)")]
		public string cnvc_ch04
		{
			get
			{
				return this._cnvc_ch04;
			}
			set
			{
				if ((this._cnvc_ch04 != value))
				{
					this.Oncnvc_ch04Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch04 = value;
					this.SendPropertyChanged("cnvc_ch04");
					this.Oncnvc_ch04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch05", DbType="VarChar(16)")]
		public string cnvc_ch05
		{
			get
			{
				return this._cnvc_ch05;
			}
			set
			{
				if ((this._cnvc_ch05 != value))
				{
					this.Oncnvc_ch05Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch05 = value;
					this.SendPropertyChanged("cnvc_ch05");
					this.Oncnvc_ch05Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ch06", DbType="VarChar(16)")]
		public string cnvc_ch06
		{
			get
			{
				return this._cnvc_ch06;
			}
			set
			{
				if ((this._cnvc_ch06 != value))
				{
					this.Oncnvc_ch06Changing(value);
					this.SendPropertyChanging();
					this._cnvc_ch06 = value;
					this.SendPropertyChanged("cnvc_ch06");
					this.Oncnvc_ch06Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_op_onof", DbType="VarChar(8)")]
		public string cnvc_op_onof
		{
			get
			{
				return this._cnvc_op_onof;
			}
			set
			{
				if ((this._cnvc_op_onof != value))
				{
					this.Oncnvc_op_onofChanging(value);
					this.SendPropertyChanging();
					this._cnvc_op_onof = value;
					this.SendPropertyChanged("cnvc_op_onof");
					this.Oncnvc_op_onofChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_op_eror", DbType="VarChar(8)")]
		public string cnvc_op_eror
		{
			get
			{
				return this._cnvc_op_eror;
			}
			set
			{
				if ((this._cnvc_op_eror != value))
				{
					this.Oncnvc_op_erorChanging(value);
					this.SendPropertyChanging();
					this._cnvc_op_eror = value;
					this.SendPropertyChanged("cnvc_op_eror");
					this.Oncnvc_op_erorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_job_no", DbType="VarChar(60)")]
		public string cnvc_job_no
		{
			get
			{
				return this._cnvc_job_no;
			}
			set
			{
				if ((this._cnvc_job_no != value))
				{
					this.Oncnvc_job_noChanging(value);
					this.SendPropertyChanging();
					this._cnvc_job_no = value;
					this.SendPropertyChanged("cnvc_job_no");
					this.Oncnvc_job_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_jobno", DbType="VarChar(188)")]
		public string cnvc_jobno
		{
			get
			{
				return this._cnvc_jobno;
			}
			set
			{
				if ((this._cnvc_jobno != value))
				{
					this.Oncnvc_jobnoChanging(value);
					this.SendPropertyChanging();
					this._cnvc_jobno = value;
					this.SendPropertyChanged("cnvc_jobno");
					this.Oncnvc_jobnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_buf_palt", DbType="VarChar(50)")]
		public string cnvc_buf_palt
		{
			get
			{
				return this._cnvc_buf_palt;
			}
			set
			{
				if ((this._cnvc_buf_palt != value))
				{
					this.Oncnvc_buf_paltChanging(value);
					this.SendPropertyChanging();
					this._cnvc_buf_palt = value;
					this.SendPropertyChanged("cnvc_buf_palt");
					this.Oncnvc_buf_paltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ist_redy", DbType="VarChar(5)")]
		public string cnvc_ist_redy
		{
			get
			{
				return this._cnvc_ist_redy;
			}
			set
			{
				if ((this._cnvc_ist_redy != value))
				{
					this.Oncnvc_ist_redyChanging(value);
					this.SendPropertyChanging();
					this._cnvc_ist_redy = value;
					this.SendPropertyChanged("cnvc_ist_redy");
					this.Oncnvc_ist_redyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ist_palt", DbType="VarChar(5)")]
		public string cnvc_ist_palt
		{
			get
			{
				return this._cnvc_ist_palt;
			}
			set
			{
				if ((this._cnvc_ist_palt != value))
				{
					this.Oncnvc_ist_paltChanging(value);
					this.SendPropertyChanging();
					this._cnvc_ist_palt = value;
					this.SendPropertyChanged("cnvc_ist_palt");
					this.Oncnvc_ist_paltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ost_redy", DbType="VarChar(5)")]
		public string cnvc_ost_redy
		{
			get
			{
				return this._cnvc_ost_redy;
			}
			set
			{
				if ((this._cnvc_ost_redy != value))
				{
					this.Oncnvc_ost_redyChanging(value);
					this.SendPropertyChanging();
					this._cnvc_ost_redy = value;
					this.SendPropertyChanged("cnvc_ost_redy");
					this.Oncnvc_ost_redyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_ost_palt", DbType="VarChar(5)")]
		public string cnvc_ost_palt
		{
			get
			{
				return this._cnvc_ost_palt;
			}
			set
			{
				if ((this._cnvc_ost_palt != value))
				{
					this.Oncnvc_ost_paltChanging(value);
					this.SendPropertyChanging();
					this._cnvc_ost_palt = value;
					this.SendPropertyChanged("cnvc_ost_palt");
					this.Oncnvc_ost_paltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_21_rqst", DbType="VarChar(1)")]
		public string cnvc_21_rqst
		{
			get
			{
				return this._cnvc_21_rqst;
			}
			set
			{
				if ((this._cnvc_21_rqst != value))
				{
					this.Oncnvc_21_rqstChanging(value);
					this.SendPropertyChanging();
					this._cnvc_21_rqst = value;
					this.SendPropertyChanged("cnvc_21_rqst");
					this.Oncnvc_21_rqstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_22_rqst", DbType="VarChar(1)")]
		public string cnvc_22_rqst
		{
			get
			{
				return this._cnvc_22_rqst;
			}
			set
			{
				if ((this._cnvc_22_rqst != value))
				{
					this.Oncnvc_22_rqstChanging(value);
					this.SendPropertyChanging();
					this._cnvc_22_rqst = value;
					this.SendPropertyChanged("cnvc_22_rqst");
					this.Oncnvc_22_rqstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_remote", DbType="VarChar(1)")]
		public string cnvc_remote
		{
			get
			{
				return this._cnvc_remote;
			}
			set
			{
				if ((this._cnvc_remote != value))
				{
					this.Oncnvc_remoteChanging(value);
					this.SendPropertyChanging();
					this._cnvc_remote = value;
					this.SendPropertyChanged("cnvc_remote");
					this.Oncnvc_remoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_stop", DbType="VarChar(1)")]
		public string cnvc_stop
		{
			get
			{
				return this._cnvc_stop;
			}
			set
			{
				if ((this._cnvc_stop != value))
				{
					this.Oncnvc_stopChanging(value);
					this.SendPropertyChanging();
					this._cnvc_stop = value;
					this.SendPropertyChanged("cnvc_stop");
					this.Oncnvc_stopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_comm", DbType="VarChar(1)")]
		public string cnvc_comm
		{
			get
			{
				return this._cnvc_comm;
			}
			set
			{
				if ((this._cnvc_comm != value))
				{
					this.Oncnvc_commChanging(value);
					this.SendPropertyChanging();
					this._cnvc_comm = value;
					this.SendPropertyChanged("cnvc_comm");
					this.Oncnvc_commChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cnvc_24_rqst", DbType="VarChar(1)")]
		public string cnvc_24_rqst
		{
			get
			{
				return this._cnvc_24_rqst;
			}
			set
			{
				if ((this._cnvc_24_rqst != value))
				{
					this.Oncnvc_24_rqstChanging(value);
					this.SendPropertyChanging();
					this._cnvc_24_rqst = value;
					this.SendPropertyChanged("cnvc_24_rqst");
					this.Oncnvc_24_rqstChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbscrc")]
	public partial class tbscrc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _scrc_no;
		
		private string _scrc_mode;
		
		private string _scrc_gubn;
		
		private string _scrc_io;
		
		private string _scrc_onln;
		
		private string _scrc_pwron;
		
		private string _scrc_emer;
		
		private string _scrc_stat;
		
		private string _scrc_palt;
		
		private string _scrc_posi;
		
		private string _scrc_eror;
		
		private string _scrc_ecod;
		
		private string _scrc_stop;
		
		private string _scrc_iuse;
		
		private string _scrc_ouse;
		
		private string _scrc_lstk;
		
		private string _scrc_pltn;
		
		private string _scrc_jno;
		
		private string _scrc_indx;
		
		private string _scrc_fstn;
		
		private string _scrc_tstn;
		
		private string _scrc_xmov;
		
		private string _scrc_mesg;
		
		private string _scrc_chdt;
		
		private string _scrc_comm;
		
		private string _scrc_rset;
		
    #region 확장성 메서드 정의
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onscrc_noChanging(string value);
    partial void Onscrc_noChanged();
    partial void Onscrc_modeChanging(string value);
    partial void Onscrc_modeChanged();
    partial void Onscrc_gubnChanging(string value);
    partial void Onscrc_gubnChanged();
    partial void Onscrc_ioChanging(string value);
    partial void Onscrc_ioChanged();
    partial void Onscrc_onlnChanging(string value);
    partial void Onscrc_onlnChanged();
    partial void Onscrc_pwronChanging(string value);
    partial void Onscrc_pwronChanged();
    partial void Onscrc_emerChanging(string value);
    partial void Onscrc_emerChanged();
    partial void Onscrc_statChanging(string value);
    partial void Onscrc_statChanged();
    partial void Onscrc_paltChanging(string value);
    partial void Onscrc_paltChanged();
    partial void Onscrc_posiChanging(string value);
    partial void Onscrc_posiChanged();
    partial void Onscrc_erorChanging(string value);
    partial void Onscrc_erorChanged();
    partial void Onscrc_ecodChanging(string value);
    partial void Onscrc_ecodChanged();
    partial void Onscrc_stopChanging(string value);
    partial void Onscrc_stopChanged();
    partial void Onscrc_iuseChanging(string value);
    partial void Onscrc_iuseChanged();
    partial void Onscrc_ouseChanging(string value);
    partial void Onscrc_ouseChanged();
    partial void Onscrc_lstkChanging(string value);
    partial void Onscrc_lstkChanged();
    partial void Onscrc_pltnChanging(string value);
    partial void Onscrc_pltnChanged();
    partial void Onscrc_jnoChanging(string value);
    partial void Onscrc_jnoChanged();
    partial void Onscrc_indxChanging(string value);
    partial void Onscrc_indxChanged();
    partial void Onscrc_fstnChanging(string value);
    partial void Onscrc_fstnChanged();
    partial void Onscrc_tstnChanging(string value);
    partial void Onscrc_tstnChanged();
    partial void Onscrc_xmovChanging(string value);
    partial void Onscrc_xmovChanged();
    partial void Onscrc_mesgChanging(string value);
    partial void Onscrc_mesgChanged();
    partial void Onscrc_chdtChanging(string value);
    partial void Onscrc_chdtChanged();
    partial void Onscrc_commChanging(string value);
    partial void Onscrc_commChanged();
    partial void Onscrc_rsetChanging(string value);
    partial void Onscrc_rsetChanged();
    #endregion
		
		public tbscrc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_no", DbType="VarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string scrc_no
		{
			get
			{
				return this._scrc_no;
			}
			set
			{
				if ((this._scrc_no != value))
				{
					this.Onscrc_noChanging(value);
					this.SendPropertyChanging();
					this._scrc_no = value;
					this.SendPropertyChanged("scrc_no");
					this.Onscrc_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_mode", DbType="VarChar(2)")]
		public string scrc_mode
		{
			get
			{
				return this._scrc_mode;
			}
			set
			{
				if ((this._scrc_mode != value))
				{
					this.Onscrc_modeChanging(value);
					this.SendPropertyChanging();
					this._scrc_mode = value;
					this.SendPropertyChanged("scrc_mode");
					this.Onscrc_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_gubn", DbType="VarChar(1)")]
		public string scrc_gubn
		{
			get
			{
				return this._scrc_gubn;
			}
			set
			{
				if ((this._scrc_gubn != value))
				{
					this.Onscrc_gubnChanging(value);
					this.SendPropertyChanging();
					this._scrc_gubn = value;
					this.SendPropertyChanged("scrc_gubn");
					this.Onscrc_gubnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_io", DbType="VarChar(1)")]
		public string scrc_io
		{
			get
			{
				return this._scrc_io;
			}
			set
			{
				if ((this._scrc_io != value))
				{
					this.Onscrc_ioChanging(value);
					this.SendPropertyChanging();
					this._scrc_io = value;
					this.SendPropertyChanged("scrc_io");
					this.Onscrc_ioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_onln", DbType="VarChar(1)")]
		public string scrc_onln
		{
			get
			{
				return this._scrc_onln;
			}
			set
			{
				if ((this._scrc_onln != value))
				{
					this.Onscrc_onlnChanging(value);
					this.SendPropertyChanging();
					this._scrc_onln = value;
					this.SendPropertyChanged("scrc_onln");
					this.Onscrc_onlnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_pwron", DbType="VarChar(1)")]
		public string scrc_pwron
		{
			get
			{
				return this._scrc_pwron;
			}
			set
			{
				if ((this._scrc_pwron != value))
				{
					this.Onscrc_pwronChanging(value);
					this.SendPropertyChanging();
					this._scrc_pwron = value;
					this.SendPropertyChanged("scrc_pwron");
					this.Onscrc_pwronChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_emer", DbType="VarChar(1)")]
		public string scrc_emer
		{
			get
			{
				return this._scrc_emer;
			}
			set
			{
				if ((this._scrc_emer != value))
				{
					this.Onscrc_emerChanging(value);
					this.SendPropertyChanging();
					this._scrc_emer = value;
					this.SendPropertyChanged("scrc_emer");
					this.Onscrc_emerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_stat", DbType="VarChar(4)")]
		public string scrc_stat
		{
			get
			{
				return this._scrc_stat;
			}
			set
			{
				if ((this._scrc_stat != value))
				{
					this.Onscrc_statChanging(value);
					this.SendPropertyChanging();
					this._scrc_stat = value;
					this.SendPropertyChanged("scrc_stat");
					this.Onscrc_statChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_palt", DbType="VarChar(1)")]
		public string scrc_palt
		{
			get
			{
				return this._scrc_palt;
			}
			set
			{
				if ((this._scrc_palt != value))
				{
					this.Onscrc_paltChanging(value);
					this.SendPropertyChanging();
					this._scrc_palt = value;
					this.SendPropertyChanged("scrc_palt");
					this.Onscrc_paltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_posi", DbType="VarChar(4)")]
		public string scrc_posi
		{
			get
			{
				return this._scrc_posi;
			}
			set
			{
				if ((this._scrc_posi != value))
				{
					this.Onscrc_posiChanging(value);
					this.SendPropertyChanging();
					this._scrc_posi = value;
					this.SendPropertyChanged("scrc_posi");
					this.Onscrc_posiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_eror", DbType="VarChar(1)")]
		public string scrc_eror
		{
			get
			{
				return this._scrc_eror;
			}
			set
			{
				if ((this._scrc_eror != value))
				{
					this.Onscrc_erorChanging(value);
					this.SendPropertyChanging();
					this._scrc_eror = value;
					this.SendPropertyChanged("scrc_eror");
					this.Onscrc_erorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_ecod", DbType="VarChar(4)")]
		public string scrc_ecod
		{
			get
			{
				return this._scrc_ecod;
			}
			set
			{
				if ((this._scrc_ecod != value))
				{
					this.Onscrc_ecodChanging(value);
					this.SendPropertyChanging();
					this._scrc_ecod = value;
					this.SendPropertyChanged("scrc_ecod");
					this.Onscrc_ecodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_stop", DbType="VarChar(1)")]
		public string scrc_stop
		{
			get
			{
				return this._scrc_stop;
			}
			set
			{
				if ((this._scrc_stop != value))
				{
					this.Onscrc_stopChanging(value);
					this.SendPropertyChanging();
					this._scrc_stop = value;
					this.SendPropertyChanged("scrc_stop");
					this.Onscrc_stopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_iuse", DbType="VarChar(1)")]
		public string scrc_iuse
		{
			get
			{
				return this._scrc_iuse;
			}
			set
			{
				if ((this._scrc_iuse != value))
				{
					this.Onscrc_iuseChanging(value);
					this.SendPropertyChanging();
					this._scrc_iuse = value;
					this.SendPropertyChanged("scrc_iuse");
					this.Onscrc_iuseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_ouse", DbType="VarChar(1)")]
		public string scrc_ouse
		{
			get
			{
				return this._scrc_ouse;
			}
			set
			{
				if ((this._scrc_ouse != value))
				{
					this.Onscrc_ouseChanging(value);
					this.SendPropertyChanging();
					this._scrc_ouse = value;
					this.SendPropertyChanged("scrc_ouse");
					this.Onscrc_ouseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_lstk", DbType="VarChar(6)")]
		public string scrc_lstk
		{
			get
			{
				return this._scrc_lstk;
			}
			set
			{
				if ((this._scrc_lstk != value))
				{
					this.Onscrc_lstkChanging(value);
					this.SendPropertyChanging();
					this._scrc_lstk = value;
					this.SendPropertyChanged("scrc_lstk");
					this.Onscrc_lstkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_pltn", DbType="VarChar(8)")]
		public string scrc_pltn
		{
			get
			{
				return this._scrc_pltn;
			}
			set
			{
				if ((this._scrc_pltn != value))
				{
					this.Onscrc_pltnChanging(value);
					this.SendPropertyChanging();
					this._scrc_pltn = value;
					this.SendPropertyChanged("scrc_pltn");
					this.Onscrc_pltnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_jno", DbType="VarChar(18)")]
		public string scrc_jno
		{
			get
			{
				return this._scrc_jno;
			}
			set
			{
				if ((this._scrc_jno != value))
				{
					this.Onscrc_jnoChanging(value);
					this.SendPropertyChanging();
					this._scrc_jno = value;
					this.SendPropertyChanged("scrc_jno");
					this.Onscrc_jnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_indx", DbType="VarChar(4)")]
		public string scrc_indx
		{
			get
			{
				return this._scrc_indx;
			}
			set
			{
				if ((this._scrc_indx != value))
				{
					this.Onscrc_indxChanging(value);
					this.SendPropertyChanging();
					this._scrc_indx = value;
					this.SendPropertyChanged("scrc_indx");
					this.Onscrc_indxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_fstn", DbType="VarChar(2)")]
		public string scrc_fstn
		{
			get
			{
				return this._scrc_fstn;
			}
			set
			{
				if ((this._scrc_fstn != value))
				{
					this.Onscrc_fstnChanging(value);
					this.SendPropertyChanging();
					this._scrc_fstn = value;
					this.SendPropertyChanged("scrc_fstn");
					this.Onscrc_fstnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_tstn", DbType="VarChar(2)")]
		public string scrc_tstn
		{
			get
			{
				return this._scrc_tstn;
			}
			set
			{
				if ((this._scrc_tstn != value))
				{
					this.Onscrc_tstnChanging(value);
					this.SendPropertyChanging();
					this._scrc_tstn = value;
					this.SendPropertyChanged("scrc_tstn");
					this.Onscrc_tstnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_xmov", DbType="VarChar(1)")]
		public string scrc_xmov
		{
			get
			{
				return this._scrc_xmov;
			}
			set
			{
				if ((this._scrc_xmov != value))
				{
					this.Onscrc_xmovChanging(value);
					this.SendPropertyChanging();
					this._scrc_xmov = value;
					this.SendPropertyChanged("scrc_xmov");
					this.Onscrc_xmovChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_mesg", DbType="VarChar(60)")]
		public string scrc_mesg
		{
			get
			{
				return this._scrc_mesg;
			}
			set
			{
				if ((this._scrc_mesg != value))
				{
					this.Onscrc_mesgChanging(value);
					this.SendPropertyChanging();
					this._scrc_mesg = value;
					this.SendPropertyChanged("scrc_mesg");
					this.Onscrc_mesgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_chdt", DbType="VarChar(44)")]
		public string scrc_chdt
		{
			get
			{
				return this._scrc_chdt;
			}
			set
			{
				if ((this._scrc_chdt != value))
				{
					this.Onscrc_chdtChanging(value);
					this.SendPropertyChanging();
					this._scrc_chdt = value;
					this.SendPropertyChanged("scrc_chdt");
					this.Onscrc_chdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_comm", DbType="VarChar(1)")]
		public string scrc_comm
		{
			get
			{
				return this._scrc_comm;
			}
			set
			{
				if ((this._scrc_comm != value))
				{
					this.Onscrc_commChanging(value);
					this.SendPropertyChanging();
					this._scrc_comm = value;
					this.SendPropertyChanged("scrc_comm");
					this.Onscrc_commChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scrc_rset", DbType="VarChar(1)")]
		public string scrc_rset
		{
			get
			{
				return this._scrc_rset;
			}
			set
			{
				if ((this._scrc_rset != value))
				{
					this.Onscrc_rsetChanging(value);
					this.SendPropertyChanging();
					this._scrc_rset = value;
					this.SendPropertyChanged("scrc_rset");
					this.Onscrc_rsetChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
