#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class DB2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DB2DataContext() : 
				base("Data Source=YSSEUNG-THINK\\SQLEXPRESS;Initial Catalog=K5;User ID=sa;Password=edps1" +
						"986", mappingSource)
		{
			OnCreated();
		}
		
		public DB2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime10")]
		public int p_curgetdatetime10([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime14")]
		public int p_curgetdatetime14([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(14)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_curgetdatetime19")]
		public int p_curgetdatetime19([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(19)")] ref string dtstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dtstr);
			dtstr = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.p_get_indx_jno")]
		public int p_get_indx_jno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string ac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(18)")] ref string rstr)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ac, rstr);
			rstr = ((string)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
